# Generated by Django 3.2.5 on 2022-03-19 13:28

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=100, verbose_name='توضیح کوتاه')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'صورتحساب ها',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',), 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ('-id',), 'verbose_name': 'روز کاری', 'verbose_name_plural': 'روزهای کاری'},
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='مقدار')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='projects.invoice', verbose_name='صورتحساب')),
            ],
            options={
                'verbose_name': 'جزئیات صورتحساب',
                'verbose_name_plural': 'جزئیات صورتحساب ها',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project', verbose_name='پروژه'),
        ),
    ]
