# Generated by Django 3.2.5 on 2022-03-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220323_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created',), 'verbose_name': 'صورتحساب', 'verbose_name_plural': 'صورتحساب ها'},
        ),
    ]
