# Generated by Django 3.2.5 on 2022-03-13 14:08

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=13)),
                ('code', models.TextField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد تائید',
                'verbose_name_plural': 'کد تائید ها',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='accounts/avatars/default.jpg', upload_to=accounts.models.upload_avatar_path, validators=[accounts.validators.validate_avatar], verbose_name='avatar'),
        ),
    ]
