# Generated by Django 3.2.5 on 2022-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220313_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
