# Generated by Django 3.2.5 on 2022-03-23 17:51

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_phoneotp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='accounts/avatars/default.jpg', upload_to=accounts.models.upload_avatar_path, validators=[accounts.validators.validate_avatar], verbose_name='تصویر پروفایل'),
        ),
    ]
