# Generated by Django 3.2.5 on 2022-06-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آیپی')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='ادرس صفحه')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user_agent', models.CharField(max_length=255, verbose_name='اطلاعات سیستم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیپی',
                'verbose_name_plural': 'آیپی ها',
            },
        ),
    ]
