# Generated by Django 3.2.5 on 2022-05-29 14:39

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kala',
            fields=[
                ('id', models.CharField(default=extensions.utils.generate_kala_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='QRCode')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('filter', models.CharField(choices=[('0', 'انبار مصرفی'), ('1', 'انبار ابزار')], max_length=10, verbose_name='انبار')),
            ],
        ),
    ]
