# Generated by Django 3.2.5 on 2022-05-29 14:55

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kala',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterField(
            model_name='kala',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='kala/qr/', verbose_name='QRCode'),
        ),
        migrations.CreateModel(
            name='KalaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('short_description', models.CharField(max_length=150, verbose_name='توضیح سابقه')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kala_histories', to='storeroom.kala', verbose_name='کالا')),
            ],
        ),
        migrations.CreateModel(
            name='KalaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='واحد')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('total', models.BigIntegerField(verbose_name='جمع')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kala_details', to='storeroom.kala', verbose_name='کالا')),
            ],
        ),
    ]
