# Generated by Django 3.2.5 on 2022-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0002_auto_20220529_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kala',
            options={'ordering': ('-created',), 'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='kaladetail',
            options={'verbose_name': 'جزئیات کالا', 'verbose_name_plural': 'جزئیات کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='kalahistory',
            options={'verbose_name': 'سابقه کالا', 'verbose_name_plural': 'سابقه کالا ها'},
        ),
        migrations.AddField(
            model_name='kala',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kala',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
