# Generated by Django 3.2.5 on 2022-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0003_auto_20220529_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaladetail',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='kaladetail',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='kaladetail',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جمع قیمت'),
        ),
    ]
