# Generated by Django 3.2.5 on 2022-03-17 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دپارتمان')),
                ('description', models.TextField(verbose_name='توضیحات دپارتمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_owner', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('staff_users', models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ارشد')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان ها',
            },
        ),
    ]
